services:
  web:
    build: .
    depends_on:
      - redis
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/1
    volumes:
      - .:/rails
      - mecab_api_storage:/rails/storage

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"

volumes:
  mecab_api_storage:
